"""empty message

Revision ID: 068aa68dce1d
Revises: 1b3e8397d4d8
Create Date: 2021-05-21 11:30:31.317737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '068aa68dce1d'
down_revision = '1b3e8397d4d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('disabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'disabled')
    # ### end Alembic commands ###
